# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0a0352ccbf39759eae98eff34fad56cf5b4b7d9737b5ae7034986e0deb197cac0f1f5805e3fb75e2558b48901dadce532da9a7ba387b8dcd5b3e543fd8b927b

test:
  secret_key_base: 1966193ba6da10b4a684c4a248abe86d35a1693ffc13f871c8d876e2b72a5aae1ec13322cefa0793bd1d5ce845d3fd473676b606b7d59ad7e33af180c23a2454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
